groups:
  - name: tunein
    reviewers: 1
    usernames:
      - rajakumari526
      - ysmounika
      - Mounikakatta25
      
  - name: approver 
    reviewers: 1
    usernames:
      - olezvinskyi
      - venkatvaddi666
      - srivaniKalyampudi

