package com.tunein.mobile.binds.page;

import com.google.inject.AbstractModule;
import com.tunein.mobile.pages.common.authentication.*;
import com.tunein.mobile.pages.common.browsies.*;
import com.tunein.mobile.pages.common.contentprofile.AffiliatesPage;
import com.tunein.mobile.pages.common.contentprofile.ContentProfilePage;
import com.tunein.mobile.pages.common.contentprofile.MoreDropDownPage;
import com.tunein.mobile.pages.common.explorer.ExplorerMiniPlayerPage;
import com.tunein.mobile.pages.common.explorer.ExplorerPage;
import com.tunein.mobile.pages.common.homepage.CarModePage;
import com.tunein.mobile.pages.common.homepage.HomePage;
import com.tunein.mobile.pages.common.library.*;
import com.tunein.mobile.pages.common.navigation.ContentsListPage;
import com.tunein.mobile.pages.common.navigation.TeamsPage;
import com.tunein.mobile.pages.common.nowplaying.MiniPlayerPage;
import com.tunein.mobile.pages.common.nowplaying.NowPlayingPage;
import com.tunein.mobile.pages.common.premium.PremiumPage;
import com.tunein.mobile.pages.common.search.SearchPage;
import com.tunein.mobile.pages.common.subscription.AlexaUpsellPage;
import com.tunein.mobile.pages.common.subscription.UpsellPage;
import com.tunein.mobile.pages.common.userprofile.*;
import com.tunein.mobile.pages.dialog.common.CustomUrlFavoriteDialog;
import com.tunein.mobile.pages.dialog.common.ListenLiveRewindModalDialog;
import com.tunein.mobile.pages.dialog.ios.IosCustomUrlFavoriteDialog;
import com.tunein.mobile.pages.dialog.ios.IosListenLiveRewindModalDialog;
import com.tunein.mobile.pages.ios.authentication.*;
import com.tunein.mobile.pages.ios.browsies.*;
import com.tunein.mobile.pages.ios.contentprofile.IosAffiliatesPage;
import com.tunein.mobile.pages.ios.contentprofile.IosContentProfilePage;
import com.tunein.mobile.pages.ios.contentprofile.IosMoreDropDownPage;
import com.tunein.mobile.pages.ios.explorer.IosExplorerMiniPlayerPage;
import com.tunein.mobile.pages.ios.explorer.IosExplorerPage;
import com.tunein.mobile.pages.ios.homepage.IosCarModePage;
import com.tunein.mobile.pages.ios.homepage.IosHomePage;
import com.tunein.mobile.pages.ios.library.*;
import com.tunein.mobile.pages.ios.navigation.IosContentsListPage;
import com.tunein.mobile.pages.ios.navigation.IosTeamsPage;
import com.tunein.mobile.pages.ios.nowplaying.IosMiniPlayerPage;
import com.tunein.mobile.pages.ios.nowplaying.IosNowPlayingPage;
import com.tunein.mobile.pages.ios.premium.IosPremiumPage;
import com.tunein.mobile.pages.ios.search.IosSearchPage;
import com.tunein.mobile.pages.ios.subscription.IosAlexaUpsellPage;
import com.tunein.mobile.pages.ios.subscription.IosUpsellPage;
import com.tunein.mobile.pages.ios.userprofile.*;

public class IosPageBinds extends AbstractModule {

    protected void configure() {
        super.configure();
        bind(SignInPage.class).to(IosSignInPage.class).asEagerSingleton();
        bind(UserProfilePage.class).to(IosUserProfilePage.class).asEagerSingleton();
        bind(HomePage.class).to(IosHomePage.class).asEagerSingleton();
        bind(RegWallPage.class).to(IosRegWallPage.class).asEagerSingleton();
        bind(SignInSignUpSuccessPage.class).to(IosSignInSignUpSuccessPage.class).asEagerSingleton();
        bind(UpsellPage.class).to(IosUpsellPage.class).asEagerSingleton();
        bind(AlexaUpsellPage.class).to(IosAlexaUpsellPage.class).asEagerSingleton();
        bind(SearchPage.class).to(IosSearchPage.class).asEagerSingleton();
        bind(NowPlayingPage.class).to(IosNowPlayingPage.class).asEagerSingleton();
        bind(ContentProfilePage.class).to(IosContentProfilePage.class).asEagerSingleton();
        bind(AffiliatesPage.class).to(IosAffiliatesPage.class).asEagerSingleton();
        bind(MiniPlayerPage.class).to(IosMiniPlayerPage.class).asEagerSingleton();
        bind(SignUpPage.class).to(IosSignUpPage.class).asEagerSingleton();
        bind(FacebookAuthenticationPage.class).to(IosFacebookAuthenticationPage.class).asEagerSingleton();
        bind(GoogleAuthenticationPage.class).to(IosGoogleAuthenticationPage.class).asEagerSingleton();
        bind(EditUserProfilePage.class).to(IosEditUserProfilePage.class).asEagerSingleton();
        bind(SettingsPage.class).to(IosSettingsPage.class).asEagerSingleton();
        bind(TuneInPremiumPage.class).to(IosTuneInPremiumPage.class).asEagerSingleton();
        bind(AboutPage.class).to(IosAboutPage.class).asEagerSingleton();
        bind(HelpCenterWebPage.class).to(IosHelpCenterWebPage.class).asEagerSingleton();
        bind(LibraryPage.class).to(IosLibraryPage.class).asEagerSingleton();
        bind(PremiumPage.class).to(IosPremiumPage.class).asEagerSingleton();
        bind(CustomUrlAddPage.class).to(IosCustomUrlAddPage.class).asEagerSingleton();
        bind(CustomUrlFavoriteDialog.class).to(IosCustomUrlFavoriteDialog.class).asEagerSingleton();
        bind(LocalRadioPage.class).to(IosLocalRadioPage.class).asEagerSingleton();
        bind(SportsPage.class).to(IosSportsPage.class).asEagerSingleton();
        bind(IheartRadioPage.class).to(IosIheartRadioPage.class).asEagerSingleton();
        bind(NewsAndTalkPage.class).to(IosNewsAndTalkPage.class).asEagerSingleton();
        bind(PodcastsPage.class).to(IosPodcastsPage.class).asEagerSingleton();
        bind(MusicPage.class).to(IosMusicPage.class).asEagerSingleton();
        bind(TrendingPage.class).to(IosTrendingPage.class).asEagerSingleton();
        bind(ByLocationPage.class).to(IosByLocationPage.class).asEagerSingleton();
        bind(ByLanguagePage.class).to(IosByLanguagePage.class).asEagerSingleton();
        bind(PrivacyPolicyPage.class).to(IosPrivacyPolicyPage.class).asEagerSingleton();
        bind(TermsOfServicePage.class).to(IosTermsOfServicePage.class).asEagerSingleton();
        bind(FavoritesPage.class).to(IosFavoritesPage.class).asEagerSingleton();
        bind(ForgotPasswordPage.class).to(IosForgotPasswordPage.class).asEagerSingleton();
        bind(MoreDropDownPage.class).to(IosMoreDropDownPage.class).asEagerSingleton();
        bind(ContentsListPage.class).to(IosContentsListPage.class).asEagerSingleton();
        bind(TeamsPage.class).to(IosTeamsPage.class).asEagerSingleton();
        bind(CarModePage.class).to(IosCarModePage.class).asEagerSingleton();
        bind(RecentsPage.class).to(IosRecentsPage.class).asEagerSingleton();
        bind(RadioPage.class).to(IosRadioPage.class).asEagerSingleton();
        bind(LegalNoticesPage.class).to(IosLegalNoticesPage.class).asEagerSingleton();
        bind(DownloadsPage.class).to(IosDownloadsPage.class).asEagerSingleton();
        bind(ListenLiveRewindModalDialog.class).to(IosListenLiveRewindModalDialog.class).asEagerSingleton();
        bind(ExplorerPage.class).to(IosExplorerPage.class).asEagerSingleton();
        bind(ExplorerMiniPlayerPage.class).to(IosExplorerMiniPlayerPage.class).asEagerSingleton();
    }
}
