name: Add required PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-small-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: "Android,iOS,maintenance,reporting"
          REQUIRED_LABELS_ALL: "needs review"
